import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    lang: 'en',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    catalog: 'Catalog',
    customers: 'Customers',
    notifications: 'Notifications',
    settings: 'Settings',
    profile: 'Profile',
    reservations: 'Reservations',
    signOut: 'Sign Out',
    search: 'Search...',
    available: 'Available',
    booked: 'Booked',
    reserve: 'Reserve',
    dailyRate: 'Daily Rate',
    seats: 'Seats',
    transmission: 'Transmission',
    range: 'Range',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirmSignOut: 'Confirm Sign Out',
    areYouSure: 'Are you sure you want to end your current session?',
    fleetManagement: 'Fleet Management',
    clientPortal: 'Client Portal',
    // TopBar
    lightMode: 'Light',
    darkMode: 'Dark',
    // Catalog filters
    fleetCatalog: 'Fleet Catalog',
    findAndBook: 'Find and book your ideal vehicle.',
    searchPlaceholder: 'Search...',
    availableOnly: 'Available only',
    vehiclesFound: 'vehicles found',
    allCategories: 'All categories',
    allTransmissions: 'All transmissions',
    allSeats: 'All seats',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    priceRange: 'Price Range',
    category: 'Category',
    filters: 'Filters',
    resetFilters: 'Reset',
    perDay: '/ day',
    login: 'Login',
    details: 'Details',
    loadingCatalog: 'Loading catalog...',
    noVehicles: 'No vehicles match your filters.',
    resetFiltersToSeeMore: 'Try adjusting your search criteria or resetting filters.',
    sedan: 'Sedan',
    suv: 'SUV',
    sport: 'Sport',
    luxury: 'Luxury',
    compact: 'Compact',
    electric: 'Electric',
    premium: 'Premium',
    automatic: 'Automatic',
    manual: 'Manual',
    // Reservations
    myReservations: 'My Reservations',
    viewAndManageBookings: 'View and manage your current and past bookings.',
    searchReservations: 'Search reservations...',
    loadingReservations: 'Loading your reservations...',
    bookingId: 'Booking ID',
    vehicle: 'Vehicle',
    dates: 'Dates',
    location: 'Location',
    status: 'Status',
    totalCost: 'Total Cost',
    viewDetails: 'View Details',
    noReservationsFound: 'No reservations found.',
    reservationDetails: 'Reservation Details',
    pickupReturn: 'Pickup & Return',
    costBreakdown: 'Cost Breakdown',
    serviceFee: 'Service Fee',
    free: 'FREE',
    totalCharged: 'Total Charged',
    noPayment: 'No Payment',
    resCanceled: 'Reservation was canceled',
    paymentNotYet: 'Payment Not Yet',
    waitingConfirmation: 'Waiting for confirmation',
    paymentSuccessful: 'Payment Successful',
    billedDefault: 'Billed to your default method',
    all: 'All',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    customer: 'Customer',
    phone: 'Phone',
    // Fleet
    fleetInventory: 'Fleet Inventory',
    manageVehicles: 'Manage and monitor your vehicle assets across all locations.',
    addVehicle: 'Add Vehicle',
    editVehicle: 'Edit Vehicle',
    deleteVehicle: 'Delete Vehicle',
    maintenance: 'Maintenance',
    rented: 'Rented',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    mileage: 'Mileage',
    actions: 'Actions',
    searchVehicles: 'Search vehicles...',
    loadingFleet: 'Loading fleet data...',
    vin: 'VIN',
    rateDay: 'Rate/Day',
    noVehiclesFoundCriteria: 'No vehicles found matching your criteria.',
    newVehicle: 'New Vehicle',
    brandModel: 'Brand & Model',
    close: 'Close',
    editInstead: 'Edit Instead',
    vehicleName: 'Vehicle Name',
    vinNumber: 'VIN Number',
    imageUrl: 'Image URL',
    dailyRateEuro: 'Daily Rate (€)',
    mileageKm: 'Mileage (km)',
    addToInventory: 'Add to Inventory',
    confirmDeleteVehicle: 'Are you sure you want to remove this vehicle?',
    operationFailed: 'Operation failed. Please try again.',
    quickStats: 'Quick Stats',
    revenue: 'Revenue',
    activeRentals: 'Active Rentals',
    fleetHealth: 'Fleet Health',
    customerGrowth: 'Customer Growth',
    recentActivity: 'Recent Activity',
    totalRevenue: 'Total Revenue',
    monthlyGoal: 'Monthly Goal',
    viewDetailedAnalytics: 'View Detailed Analytics',
    bookings: 'Bookings',
    newUsers: 'New Users',
    customerSatisfaction: 'Customer Satisfaction',
    basedOnFeedback: 'Based on feedback',
    overview: 'Overview',
    realTimeMetrics: 'Real-time metrics for Auto-Loc fleet operations.',
    systemCapacity: 'System Capacity',
    liveFleetOverview: 'Live fleet availability overview',
    fleetEfficiency: 'Fleet Efficiency',
    live: 'Live',
    viewAll: 'View all',
    noRecentActivity: 'No recent activity found.',
    reviewBookings: 'Review, confirm or cancel customer bookings.',
    searchByCustomer: 'Search by customer, vehicle, or ID...',
    confirmer: 'Confirm',
    complete: 'Complete',
    noActions: 'No actions',
    showing: 'Showing',
    of: 'of',
    reservationConfirmed: 'Reservation confirmed successfully',
    reservationCancelled: 'Reservation cancelled',
    showResults: 'Show {count} Results',
    auto: 'Auto',
    mainOffice: 'Main Office',
    premiumSelection: 'Premium Selection',
  },
  fr: {
    lang: 'fr',
    dashboard: 'Tableau de bord',
    inventory: 'Inventaire',
    catalog: 'Catalogue',
    customers: 'Clients',
    notifications: 'Notifications',
    settings: 'Paramètres',
    profile: 'Profil',
    reservations: 'Réservations',
    signOut: 'Déconnexion',
    search: 'Rechercher...',
    available: 'Disponible',
    booked: 'Réservé',
    reserve: 'Réserver',
    dailyRate: 'Tarif Journalier',
    seats: 'Sièges',
    transmission: 'Transmission',
    range: 'Autonomie',
    saveChanges: 'Enregistrer',
    cancel: 'Annuler',
    confirmSignOut: 'Confirmer la déconnexion',
    areYouSure: 'Êtes-vous sûr de vouloir mettre fin à votre session ?',
    fleetManagement: 'Gestion de Flotte',
    clientPortal: 'Portail Client',
    // TopBar
    lightMode: 'Clair',
    darkMode: 'Sombre',
    // Catalog filters
    fleetCatalog: 'Catalogue de Flotte',
    findAndBook: 'Trouvez et réservez votre véhicule idéal.',
    searchPlaceholder: 'Rechercher...',
    availableOnly: 'Disponible uniquement',
    vehiclesFound: 'véhicules trouvés',
    allCategories: 'Toutes catégories',
    allTransmissions: 'Toutes transmissions',
    allSeats: 'Tous sièges',
    minPrice: 'Prix Min',
    maxPrice: 'Prix Max',
    priceRange: 'Tranche de Prix',
    category: 'Catégorie',
    filters: 'Filtres',
    resetFilters: 'Réinitialiser',
    perDay: '/ jour',
    login: 'Connexion',
    details: 'Détails',
    loadingCatalog: 'Chargement du catalogue...',
    noVehicles: 'Aucun véhicule ne correspond à vos filtres.',
    resetFiltersToSeeMore: 'Essayez d\'ajuster vos critères ou de réinitialiser les filtres.',
    sedan: 'Berline',
    suv: 'SUV',
    sport: 'Sport',
    luxury: 'Luxe',
    compact: 'Compact',
    electric: 'Électrique',
    premium: 'Premium',
    automatic: 'Automatique',
    manual: 'Manuelle',
    // Reservations
    myReservations: 'Mes Réservations',
    viewAndManageBookings: 'Consultez et gérez vos réservations actuelles et passées.',
    searchReservations: 'Rechercher des réservations...',
    loadingReservations: 'Chargement de vos réservations...',
    bookingId: 'ID Réservation',
    vehicle: 'Véhicule',
    dates: 'Dates',
    location: 'Lieu',
    status: 'Statut',
    totalCost: 'Coût Total',
    viewDetails: 'Voir Détails',
    noReservationsFound: 'Aucune réservation trouvée.',
    reservationDetails: 'Détails de la Réservation',
    pickupReturn: 'Prise & Retour',
    costBreakdown: 'Détail des Coûts',
    serviceFee: 'Frais de Service',
    free: 'GRATUIT',
    totalCharged: 'Total Facturé',
    noPayment: 'Pas de Paiement',
    resCanceled: 'La réservation a été annulée',
    paymentNotYet: 'Paiement en attente',
    waitingConfirmation: 'En attente de confirmation',
    paymentSuccessful: 'Paiement Réussi',
    billedDefault: 'Facturé sur votre mode par défaut',
    all: 'Tous',
    pending: 'En attente',
    confirmed: 'Confirmé',
    completed: 'Terminé',
    cancelled: 'Annulé',
    customer: 'Client',
    phone: 'Téléphone',
    // Fleet
    fleetInventory: 'Inventaire de Flotte',
    manageVehicles: 'Gérez et surveillez vos véhicules sur tous les sites.',
    addVehicle: 'Ajouter Véhicule',
    editVehicle: 'Modifier Véhicule',
    deleteVehicle: 'Supprimer Véhicule',
    maintenance: 'Maintenance',
    rented: 'Loué',
    brand: 'Marque',
    model: 'Modèle',
    year: 'Année',
    mileage: 'Kilométrage',
    actions: 'Actions',
    searchVehicles: 'Rechercher des véhicules...',
    loadingFleet: 'Chargement des données de la flotte...',
    vin: 'N° de châssis',
    rateDay: 'Tarif/Jour',
    noVehiclesFoundCriteria: 'Aucun véhicule trouvé correspondant à vos critères.',
    newVehicle: 'Nouveau Véhicule',
    brandModel: 'Marque & Modèle',
    close: 'Fermer',
    editInstead: 'Modifier à la place',
    vehicleName: 'Nom du Véhicule',
    vinNumber: 'Numéro VIN',
    imageUrl: 'URL de l\'image',
    dailyRateEuro: 'Tarif Journalier (€)',
    mileageKm: 'Kilométrage (km)',
    addToInventory: 'Ajouter à l\'inventaire',
    confirmDeleteVehicle: 'Êtes-vous sûr de vouloir supprimer ce véhicule ?',
    operationFailed: 'L\'opération a échoué. Veuillez réessayer.',
    quickStats: 'Stats Rapides',
    revenue: 'Revenu',
    activeRentals: 'Locations Actives',
    fleetHealth: 'Santé de la Flotte',
    customerGrowth: 'Croissance Clients',
    recentActivity: 'Activité Récente',
    totalRevenue: 'Revenu Total',
    monthlyGoal: 'Objectif Mensuel',
    viewDetailedAnalytics: 'Voir Analyses Détaillées',
    bookings: 'Réservations',
    newUsers: 'Nouveaux Utilisateurs',
    customerSatisfaction: 'Satisfaction Client',
    basedOnFeedback: 'Basé sur les retours',
    overview: 'Vue d\'ensemble',
    realTimeMetrics: 'Métriques en temps réel pour les opérations de la flotte Auto-Loc.',
    systemCapacity: 'Capacité du Système',
    liveFleetOverview: 'Aperçu en direct de la disponibilité de la flotte',
    fleetEfficiency: 'Efficacité de la Flotte',
    live: 'En direct',
    viewAll: 'Voir tout',
    noRecentActivity: 'Aucune activité récente trouvée.',
    reviewBookings: 'Examinez, confirmez ou annulez les réservations des clients.',
    searchByCustomer: 'Rechercher par client, véhicule ou ID...',
    confirmer: 'Confirmer',
    complete: 'Terminer',
    noActions: 'Aucune action',
    showing: 'Affichage de',
    of: 'sur',
    reservationConfirmed: 'Réservation confirmée avec succès',
    reservationCancelled: 'Réservation annulée',
    showResults: 'Afficher {count} Résultats',
    auto: 'Auto',
    mainOffice: 'Bureau Principal',
    premiumSelection: 'Sélection Premium',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('auto_loc_lang');
    return saved || 'fr'; // Default to French as requested/implied
  });

  useEffect(() => {
    localStorage.setItem('auto_loc_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
