import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    lang: 'en',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    catalog: 'Catalog',
    customers: 'Customers',
    notifications: 'Notifications',
    settings: 'Settings',
    profile: 'Profile',
    reservations: 'Reservations',
    signOut: 'Sign Out',
    search: 'Search...',
    available: 'Available',
    booked: 'Booked',
    reserve: 'Reserve',
    dailyRate: 'Daily Rate',
    seats: 'Seats',
    transmission: 'Transmission',
    range: 'Range',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirmSignOut: 'Confirm Sign Out',
    areYouSure: 'Are you sure you want to end your session?',
    fleetManagement: 'Fleet Management',
    clientPortal: 'Client Portal',
    // TopBar
    lightMode: 'Light',
    darkMode: 'Dark',
    // Catalog filters
    fleetCatalog: 'Fleet Catalog',
    findAndBook: 'Find and book your perfect ride.',
    searchPlaceholder: 'Search...',
    availableOnly: 'Available only',
    vehiclesFound: 'vehicles found',
    allCategories: 'All Categories',
    allTransmissions: 'All Transmissions',
    allSeats: 'All Seats',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    priceRange: 'Price Range',
    category: 'Category',
    filters: 'Filters',
    resetFilters: 'Reset Filters',
    perDay: '/ day',
    login: 'Login',
    details: 'Details',
    loadingCatalog: 'Loading catalog...',
    noVehicles: 'No vehicles match your filters.',
    resetFiltersToSeeMore: 'Try adjusting your criteria or resetting filters.',
    sedan: 'Sedan',
    suv: 'SUV',
    sport: 'Sport',
    luxury: 'Luxury',
    compact: 'Compact',
    electric: 'Electric',
    premium: 'Premium',
    automatic: 'Automatic',
    manual: 'Manual',
    auto: 'Auto',
    // Reservations
    myReservations: 'My Reservations',
    viewAndManageBookings: 'View and manage your current and past bookings.',
    searchReservations: 'Search reservations...',
    loadingReservations: 'Loading reservations...',
    bookingId: 'Booking ID',
    vehicle: 'Vehicle',
    dates: 'Dates',
    location: 'Location',
    status: 'Status',
    totalCost: 'Total Cost',
    totalPrice: 'Total Price',
    viewDetails: 'View Details',
    noReservationsFound: 'No reservations found.',
    reservationDetails: 'Reservation Details',
    pickupReturn: 'Pick-up & Return',
    costBreakdown: 'Cost Breakdown',
    serviceFee: 'Service Fee',
    free: 'FREE',
    totalCharged: 'Total Charged',
    noPayment: 'No Payment',
    resCanceled: 'Reservation was cancelled',
    paymentNotYet: 'Payment Pending',
    waitingConfirmation: 'Waiting for confirmation',
    paymentSuccessful: 'Payment Successful',
    billedDefault: 'Billed to your default method',
    all: 'All',
    pending: 'Pending',
    confirmed: 'Confirmed',
    completed: 'Completed',
    cancelled: 'Cancelled',
    customer: 'Customer',
    phone: 'Phone',
    reviewBookings: 'Review, confirm, or cancel customer bookings.',
    searchByCustomer: 'Search by customer, vehicle or ID...',
    confirm: 'Confirm',
    complete: 'Complete',
    noActions: 'No actions',
    showing: 'Showing',
    of: 'of',
    reservationConfirmed: 'Reservation successfully confirmed',
    reservationCancelled: 'Reservation cancelled',
    // Fleet
    fleetInventory: 'Fleet Inventory',
    manageVehicles: 'Manage and monitor your vehicles across all locations.',
    addVehicle: 'Add Vehicle',
    editVehicle: 'Edit Vehicle',
    deleteVehicle: 'Delete Vehicle',
    maintenance: 'Maintenance',
    rented: 'Rented',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    mileage: 'Mileage',
    actions: 'Actions',
    searchVehicles: 'Search vehicles...',
    loadingFleet: 'Loading fleet data...',
    vin: 'VIN Number',
    rateDay: 'Rate/Day',
    noVehiclesFoundCriteria: 'No vehicles found matching your criteria.',
    newVehicle: 'New Vehicle',
    brandModel: 'Brand & Model',
    close: 'Close',
    editInstead: 'Edit Instead',
    vehicleName: 'Vehicle Name',
    vinNumber: 'VIN Number',
    imageUrl: 'Image URL',
    dailyRateEuro: 'Daily Rate (€)',
    mileageKm: 'Mileage (km)',
    addToInventory: 'Add to Inventory',
    confirmDeleteVehicle: 'Are you sure you want to delete this vehicle?',
    operationFailed: 'Operation failed. Please try again.',
    color: 'Color',
    quickStats: 'Quick Stats',
    revenue: 'Revenue',
    activeRentals: 'Active Rentals',
    fleetHealth: 'Fleet Health',
    customerGrowth: 'Customer Growth',
    recentActivity: 'Recent Activity',
    totalRevenue: 'Total Revenue',
    monthlyGoal: 'Monthly Goal',
    viewDetailedAnalytics: 'View Detailed Analytics',
    bookings: 'Bookings',
    newUsers: 'New Users',
    customerSatisfaction: 'Customer Satisfaction',
    basedOnFeedback: 'Based on feedback',
    overview: 'Overview',
    realTimeMetrics: 'Real-time metrics for Auto-Loc fleet operations.',
    systemCapacity: 'System Capacity',
    liveFleetOverview: 'Live fleet availability overview',
    fleetEfficiency: 'Fleet Efficiency',
    live: 'Live',
    viewAll: 'View all',
    noRecentActivity: 'No recent activity found.',
    fuel: 'Fuel',
    // Customers
    clientRoster: 'Client Roster',
    manageProfiles: 'Manage client profiles and view rental histories.',
    totalClients: 'Total Clients',
    verified: 'Verified',
    searchClients: 'Search clients...',
    loadingUsers: 'Loading users...',
    user: 'User',
    contact: 'Contact',
    joined: 'Joined',
    unnamed: 'Unnamed',
    noClientsFound: 'No clients found.',
    users: 'users',
    activeBookings: 'Active Bookings',
    maintenanceAlerts: 'Maintenance Alerts',
    utilizationRate: 'Utilization Rate',
    client: 'Client',
    // Notifications
    stayInformed: 'Stay informed about your bookings and activity.',
    allNotifications: 'All Notifications',
    markAllRead: 'Mark all as read',
    loadingNotifications: 'Loading notifications...',
    noNotificationsNow: 'No new notifications at the moment.',
    justNow: 'Just now',
    agoMin: '{n}m ago',
    agoHour: '{n}h ago',
    agoDay: '{n}d ago',
    notificationsSubtitle: 'Stay updated with your latest booking activities and account alerts.',
    unread: 'Unread',
    allCaughtUp: 'All caught up!',
    // Profile & Settings
    myProfile: 'My Profile',
    managePersonalInfo: 'Manage your personal information and preferences.',
    editProfile: 'Edit Profile',
    contactInformation: 'Contact Information',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    role: 'Role',
    accountDetails: 'Account Details',
    accountId: 'Account ID',
    accountType: 'Account Type',
    superuserAccount: 'Superuser Account',
    clientAccount: 'Client Account',
    profileSaved: 'Profile saved successfully!',
    errorSavingProfile: 'Error saving profile. Please try again.',
    notProvided: 'Not provided',
    profilePicture: 'Profile Picture',
    emailCannotBeChanged: 'Email cannot be changed',
    manageAccountPreferences: 'Manage your account and preferences.',
    account: 'Account',
    profileInformation: 'Profile Information',
    nameEmailPhone: 'Name, email, and phone',
    securityPassword: 'Security & Password',
    updateLoginCredentials: 'Update your login credentials',
    regional: 'Regional',
    choosePreferredLanguage: 'Choose your preferred language',
    choosePreferredCurrency: 'Choose your preferred currency',
    updatePassword: 'Update Password',
    passwordGuideline: 'Changing your password will update your login credentials. Make sure to use a strong password with at least 6 characters.',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordUpdated: 'Password updated successfully!',
    redirecting: 'Redirecting...',
    changePhoto: 'Change photo',
    fullName: 'Full Name',
    name: 'Name',
    security: 'Security',
    twoFactor: 'Two-Factor Auth',
    twoFactorSub: 'Add an extra layer of security',
    auditLog: 'Audit Log',
    auditLogSub: 'View recent security activity',
    systemLanguage: 'System Language',
    chooseLanguage: 'Select your preferred language',
    defaultCurrency: 'Default Currency',
    currencySub: 'Select your preferred currency',
    adminProfile: 'Admin Profile',
    adminProfileSub: 'Update your administrator profile information.',
    systemSuperuser: 'System Superuser',
    superuser: 'Superuser',
    adminEmail: 'Admin Email',
    adminName: 'Admin Name',
    contactPhone: 'Contact Phone',
    updateCredentials: 'Update Credentials',
    securityProtocol: 'Security Protocol',
    securitySub: 'Ensure your account uses a strong password. We recommend changing it every 90 days.',
    credentialsUpdated: 'Credentials updated successfully!',
    manageSettings: 'Configure system-wide settings and personal preferences.',
    profileSub: 'Update your name and contact info',
    profileUpdated: 'Profile updated successfully!',
    profileUpdateFailed: 'Failed to update profile.',
    saving: 'Saving...',
    changePassword: 'Change Password',
    changePasswordSub: 'Update your login password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    confirmNewPassword: 'Confirm New Password',
    passwordsMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    adminPrivileges: 'Administrative Privileges',
    fleetMgmt: 'Fleet Management',
    fleetMgmtSub: 'Full access to vehicle inventory and status.',
    userAdmin: 'User Administration',
    userAdminSub: 'Ability to manage client profiles and roles.',
    financialAccess: 'Financial Access',
    financialAccessSub: 'View revenue and pricing configurations.',
    sysSettings: 'System Settings',
    sysSettingsSub: 'Manage global application parameters.',
    apiAccess: 'API Access',
    apiAccessSub: 'Manage external integration keys.',
    reporting: 'Reporting',
    reportingSub: 'Generate and export performance data.',
    authHistory: 'Authorization History',
    sessionStarted: 'Session Started',
    inventoryUpdated: 'Inventory Updated',
    customerModified: 'Customer Modified',
    sysConfigChanged: 'System Config Changed',
    yesterday: 'Yesterday',
    mainOffice: 'Main Office',
    premiumSelection: 'Premium Selection',
    // Auth
    signInToAccount: 'Sign in to your account',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    password: 'Password',
    forgot: 'Forgot?',
    dontHaveAccount: "Don't have an account yet?",
    signUp: 'Sign Up',
    createClientAccount: 'Create your client account',
    signupSuccess: 'Signup successful! Please check your email to confirm your account before logging in.',
    signupError: 'An error occurred during signup.',
    backToLogin: 'Back to login',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    guest: 'Guest',
    adminPanel: 'Admin Panel',
    // Booking Flow
    rentVehicle: 'Rent {brand} {model}',
    startDate: 'Start Date',
    endDate: 'End Date',
    estTotal: 'Estimated Total Price',
    licensePhoto: "Driver's License Photo",
    docReady: 'Document Ready',
    clickToAddLicense: 'Click to add your license',
    resSent: 'Reservation Sent!',
    resSentDesc: 'Your request for {brand} {model} has been sent. Total amount: {price}.',
    confirmBooking: 'Confirm Booking',
    sending: 'Sending...',
    alreadyBookedDates: 'This vehicle is already booked for the selected dates.',
    bookingFailed: 'Booking failed. Please try again.',
    carDetails: 'Vehicle Details',
    features: 'Features',
    rentNow: 'Rent Now',
    customerReviews: 'customer reviews',
    capacity: 'Capacity',
    licensePlate: 'License Plate',
    totalPricePerDay: 'Total price per day',
    support: 'Support',
    availShort: 'Avail',
    min: 'MIN',
    max: 'MAX',
    language: 'Language',
    currency: 'Currency',
    saveProfile: 'Save Profile',
    showResults: 'Show {count} Results',
    is_required: 'is required',
  },
  fr: {
    lang: 'fr',
    dashboard: 'Tableau de bord',
    inventory: 'Inventaire',
    catalog: 'Catalogue',
    customers: 'Clients',
    notifications: 'Notifications',
    settings: 'Paramètres',
    profile: 'Profil',
    reservations: 'Réservations',
    signOut: 'Déconnexion',
    search: 'Rechercher...',
    available: 'Disponible',
    booked: 'Réservé',
    reserve: 'Réserver',
    dailyRate: 'Tarif Journalier',
    seats: 'Sièges',
    transmission: 'Transmission',
    range: 'Autonomie',
    saveChanges: 'Enregistrer',
    cancel: 'Annuler',
    confirmSignOut: 'Confirmer la déconnexion',
    areYouSure: 'Êtes-vous sûr de vouloir mettre fin à votre session ?',
    fleetManagement: 'Gestion de Flotte',
    clientPortal: 'Portail Client',
    // TopBar
    lightMode: 'Clair',
    darkMode: 'Sombre',
    // Catalog filters
    fleetCatalog: 'Catalogue de Flotte',
    findAndBook: 'Trouvez et réservez votre véhicule idéal.',
    searchPlaceholder: 'Rechercher...',
    availableOnly: 'Disponible uniquement',
    vehiclesFound: 'véhicules trouvés',
    allCategories: 'Toutes catégories',
    allTransmissions: 'Toutes transmissions',
    allSeats: 'Tous sièges',
    minPrice: 'Prix Min',
    maxPrice: 'Prix Max',
    priceRange: 'Tranche de Prix',
    category: 'Catégorie',
    filters: 'Filtres',
    resetFilters: 'Réinitialiser',
    perDay: '/ jour',
    login: 'Connexion',
    details: 'Détails',
    loadingCatalog: 'Chargement du catalogue...',
    noVehicles: 'Aucun véhicule ne correspond à vos filtres.',
    resetFiltersToSeeMore: 'Essayez d\'ajuster vos critères ou de réinitialiser les filtres.',
    sedan: 'Berline',
    suv: 'SUV',
    sport: 'Sport',
    luxury: 'Luxe',
    compact: 'Compact',
    electric: 'Électrique',
    premium: 'Premium',
    automatic: 'Automatique',
    manual: 'Manuelle',
    auto: 'Auto',
    // Reservations
    myReservations: 'Mes Réservations',
    viewAndManageBookings: 'Consultez et gérez vos réservations actuelles et passées.',
    searchReservations: 'Rechercher des réservations...',
    loadingReservations: 'Chargement des réservations...',
    bookingId: 'ID Réservation',
    vehicle: 'Véhicule',
    dates: 'Dates',
    location: 'Lieu',
    status: 'Statut',
    totalCost: 'Coût Total',
    totalPrice: 'Prix Total',
    viewDetails: 'Voir Détails',
    noReservationsFound: 'Aucune réservation trouvée.',
    reservationDetails: 'Détails de la Réservation',
    pickupReturn: 'Prise & Retour',
    costBreakdown: 'Détail des Coûts',
    serviceFee: 'Frais de Service',
    free: 'GRATUIT',
    totalCharged: 'Total Facturé',
    noPayment: 'Pas de Paiement',
    resCanceled: 'La réservation a été annulée',
    paymentNotYet: 'Paiement en attente',
    waitingConfirmation: 'En attente de confirmation',
    paymentSuccessful: 'Paiement Réussi',
    billedDefault: 'Facturé sur votre mode par défaut',
    all: 'Tous',
    pending: 'En attente',
    confirmed: 'Confirmé',
    completed: 'Terminé',
    cancelled: 'Annulé',
    customer: 'Client',
    phone: 'Téléphone',
    reviewBookings: 'Examinez, confirmez ou annulez les réservations des clients.',
    searchByCustomer: 'Rechercher par client, véhicule ou ID...',
    confirm: 'Confirmer',
    complete: 'Terminer',
    noActions: 'Aucune action',
    showing: 'Affichage de',
    of: 'sur',
    reservationConfirmed: 'Réservation confirmée avec succès',
    reservationCancelled: 'Réservation annulée',
    // Fleet
    fleetInventory: 'Inventaire de Flotte',
    manageVehicles: 'Gérez et surveillez vos véhicules sur tous les sites.',
    addVehicle: 'Ajouter Véhicule',
    editVehicle: 'Modifier Véhicule',
    deleteVehicle: 'Supprimer Véhicule',
    maintenance: 'Maintenance',
    rented: 'Loué',
    brand: 'Marque',
    model: 'Modèle',
    year: 'Année',
    mileage: 'Kilométrage',
    actions: 'Actions',
    searchVehicles: 'Rechercher des véhicules...',
    loadingFleet: 'Chargement des données de la flotte...',
    vin: 'N° de châssis',
    rateDay: 'Tarif/Jour',
    noVehiclesFoundCriteria: 'Aucun véhicule trouvé correspondant à vos critères.',
    newVehicle: 'Nouveau Véhicule',
    brandModel: 'Marque & Modèle',
    close: 'Fermer',
    editInstead: 'Modifier à la place',
    vehicleName: 'Nom du Véhicule',
    vinNumber: 'Numéro VIN',
    imageUrl: 'URL de l\'image',
    dailyRateEuro: 'Tarif Journalier (€)',
    mileageKm: 'Kilométrage (km)',
    addToInventory: 'Ajouter à l\'inventaire',
    confirmDeleteVehicle: 'Êtes-vous sûr de vouloir supprimer ce véhicule ?',
    operationFailed: 'L\'opération a échoué. Veuillez réessayer.',
    color: 'Couleur',
    quickStats: 'Stats Rapides',
    revenue: 'Revenu',
    activeRentals: 'Locations Actives',
    fleetHealth: 'Santé de la Flotte',
    customerGrowth: 'Croissance Clients',
    recentActivity: 'Activité Récente',
    totalRevenue: 'Revenu Total',
    monthlyGoal: 'Objectif Mensuel',
    viewDetailedAnalytics: 'Voir Analyses Détaillées',
    bookings: 'Réservations',
    newUsers: 'Nouveaux Utilisateurs',
    customerSatisfaction: 'Satisfaction Client',
    basedOnFeedback: 'Basé sur les retours',
    overview: 'Vue d\'ensemble',
    realTimeMetrics: 'Métriques en temps réel pour les opérations de la flotte Auto-Loc.',
    systemCapacity: 'Capacité du Système',
    liveFleetOverview: 'Aperçu en direct de la disponibilité de la flotte',
    fleetEfficiency: 'Efficacité de la Flotte',
    live: 'En direct',
    viewAll: 'Voir tout',
    noRecentActivity: 'Aucune activité récente trouvée.',
    fuel: 'Carburant',
    // Customers
    clientRoster: 'Liste des Clients',
    manageProfiles: 'Gérez les profils clients et consultez les historiques de location.',
    totalClients: 'Total Clients',
    verified: 'Vérifiés',
    searchClients: 'Rechercher des clients...',
    loadingUsers: 'Chargement des utilisateurs...',
    user: 'Utilisateur',
    contact: 'Contact',
    joined: 'Inscrit',
    unnamed: 'Sans nom',
    noClientsFound: 'Aucun client trouvé.',
    users: 'utilisateurs',
    activeBookings: 'Réservations Actives',
    maintenanceAlerts: 'Alertes Maintenance',
    utilizationRate: 'Taux d\'utilisation',
    client: 'Client',
    // Notifications
    stayInformed: 'Restez informé de vos réservations et activités.',
    allNotifications: 'Toutes les Notifications',
    markAllRead: 'Tout marquer comme lu',
    loadingNotifications: 'Chargement des notifications...',
    noNotificationsNow: 'Aucune nouvelle notification pour le moment.',
    justNow: 'À l\'instant',
    agoMin: 'Il y a {n}m',
    agoHour: 'Il y a {n}h',
    agoDay: 'Il y a {n}j',
    notificationsSubtitle: 'Restez informé de vos dernières activités de réservation et des alertes de compte.',
    unread: 'Non lu',
    allCaughtUp: 'Vous êtes à jour !',
    // Profile & Settings
    myProfile: 'Mon Profil',
    managePersonalInfo: 'Gérez vos informations personnelles et vos préférences.',
    editProfile: 'Modifier le profil',
    contactInformation: 'Informations de contact',
    emailAddress: 'Adresse e-mail',
    phoneNumber: 'Numéro de téléphone',
    role: 'Rôle',
    accountDetails: 'Détails du compte',
    accountId: 'ID du compte',
    accountType: 'Type de compte',
    superuserAccount: 'Compte Super Administrateur',
    clientAccount: 'Compte Client',
    profileSaved: 'Profil enregistré avec succès !',
    errorSavingProfile: 'Erreur lors de l\'enregistrement du profil. Veuillez réessayer.',
    notProvided: 'Non fourni',
    profilePicture: 'Photo de profil',
    emailCannotBeChanged: 'L\'e-mail ne peut pas être modifié',
    manageAccountPreferences: 'Gérez votre compte et vos préférences.',
    account: 'Compte',
    profileInformation: 'Informations du profil',
    nameEmailPhone: 'Nom, e-mail et téléphone',
    securityPassword: 'Sécurité et mot de passe',
    updateLoginCredentials: 'Mettre à jour vos identifiants de connexion',
    regional: 'Régional',
    choosePreferredLanguage: 'Choisissez votre langue préférée',
    choosePreferredCurrency: 'Choisissez votre devise préférée',
    updatePassword: 'Mettre à jour le mot de passe',
    passwordGuideline: 'Changer votre mot de passe mettra à jour vos identifiants. Assurez-vous d\'utiliser un mot de passe fort d\'au moins 6 caractères.',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    passwordUpdated: 'Mot de passe mis à jour avec succès !',
    redirecting: 'Redirection...',
    changePhoto: 'Changer la photo',
    fullName: 'Nom complet',
    name: 'Nom',
    security: 'Sécurité',
    twoFactor: 'Double Authentification',
    twoFactorSub: 'Ajoutez une couche de sécurité supplémentaire',
    auditLog: 'Journal d\'audit',
    auditLogSub: 'Voir l\'activité de sécurité récente',
    systemLanguage: 'Langue du Système',
    chooseLanguage: 'Sélectionnez votre langue préférée',
    defaultCurrency: 'Devise par Défaut',
    currencySub: 'Sélectionnez votre devise préférée',
    adminProfile: 'Profil Admin',
    adminProfileSub: 'Mettez à jour vos informations de profil administrateur.',
    systemSuperuser: 'Super Utilisateur Système',
    superuser: 'Super Utilisateur',
    adminEmail: 'Email Admin',
    adminName: 'Nom Admin',
    contactPhone: 'Téléphone de Contact',
    updateCredentials: 'Mettre à jour les Identifiants',
    securityProtocol: 'Protocole de Sécurité',
    securitySub: 'Assurez-vous que votre compte utilise un mot de passe fort. Nous recommandons de le changer tous les 90 jours.',
    credentialsUpdated: 'Identifiants mis à jour avec succès !',
    manageSettings: 'Configurez les paramètres du système et les préférences personnelles.',
    profileSub: 'Mettez à jour votre nom et vos coordonnées',
    profileUpdated: 'Profil mis à jour avec succès !',
    profileUpdateFailed: 'Échec de la mise à jour du profil.',
    saving: 'Enregistrement...',
    changePassword: 'Changer le Mot de Passe',
    changePasswordSub: 'Mettre à jour votre mot de passe de connexion',
    newPassword: 'Nouveau Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    confirmNewPassword: 'Confirmer le Nouveau Mot de Passe',
    passwordsMismatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Le mot de passe doit contenir au moins 8 caractères',
    adminPrivileges: 'Privilèges Administrateur',
    fleetMgmt: 'Gestion de Flotte',
    fleetMgmtSub: 'Accès complet à l\'inventaire et au statut des véhicules.',
    userAdmin: 'Administration des Utilisateurs',
    userAdminSub: 'Capacité à gérer les profils et rôles des clients.',
    financialAccess: 'Accès Financier',
    financialAccessSub: 'Consulter les revenus et configurations de prix.',
    sysSettings: 'Paramètres Système',
    sysSettingsSub: 'Gérer les paramètres globaux de l\'application.',
    apiAccess: 'Accès API',
    apiAccessSub: 'Gérer les clés d\'intégration externes.',
    reporting: 'Rapports',
    reportingSub: 'Générer et exporter des données de performance.',
    authHistory: 'Historique d\'Autorisation',
    sessionStarted: 'Session Démarrée',
    inventoryUpdated: 'Inventaire Mis à Jour',
    customerModified: 'Client Modifié',
    sysConfigChanged: 'Config Système Changée',
    yesterday: 'Hier',
    mainOffice: 'Bureau Principal',
    premiumSelection: 'Sélection Premium',
    // Auth
    signInToAccount: 'Connectez-vous à votre compte',
    unexpectedError: 'Une erreur inattendue est survenue. Veuillez réessayer.',
    password: 'Mot de passe',
    forgot: 'Oublié ?',
    dontHaveAccount: 'Pas encore de compte ?',
    signUp: 'S\'inscrire',
    createClientAccount: 'Créez votre compte client',
    signupSuccess: 'Inscription réussie ! Veuillez vérifier votre email pour confirmer votre compte avant de vous connecter.',
    signupError: 'Une erreur est survenue lors de l\'inscription.',
    backToLogin: 'Retour à la connexion',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    signIn: 'Se connecter',
    guest: 'Invité',
    adminPanel: 'Panneau Admin',
    // Booking Flow
    rentVehicle: 'Louer {brand} {model}',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    estTotal: 'Prix Total Estimé',
    licensePhoto: 'Photo du Permis',
    docReady: 'Document Prêt',
    clickToAddLicense: 'Cliquez pour ajouter votre permis',
    resSent: 'Réservation Envoyée !',
    resSentDesc: 'Votre demande pour {brand} {model} a été transmise. Montant total : {price}.',
    confirmBooking: 'Confirmer la Location',
    sending: 'Envoi...',
    alreadyBookedDates: 'Ce véhicule est déjà réservé pour les dates sélectionnées.',
    bookingFailed: 'La réservation a échoué. Veuillez réessayer.',
    carDetails: 'Détails du Véhicule',
    features: 'Caractéristiques',
    rentNow: 'Louer Maintenant',
    customerReviews: 'avis clients',
    capacity: 'Capacité',
    licensePlate: 'Immatriculation',
    totalPricePerDay: 'Prix total par jour',
    support: 'Support',
    availShort: 'Dispo',
    min: 'MIN',
    max: 'MAX',
    language: 'Langue',
    currency: 'Devise',
    saveProfile: 'Enregistrer le Profil',
    showResults: 'Afficher {count} Résultats',
    is_required: 'est requis',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('auto_loc_lang');
    return saved || 'fr'; // Default to French
  });

  useEffect(() => {
    localStorage.setItem('auto_loc_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key, params = {}) => {
    let text = translations[lang][key] || key;
    Object.keys(params).forEach(p => {
      text = typeof text === 'string' ? text.replace(`{${p}}`, params[p]) : text;
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
